//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HIMSDBEntities : DbContext
    {
        public HIMSDBEntities()
            : base("name=HIMSDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<HospitalDetail> HospitalDetails { get; set; }
        public virtual DbSet<Ipd_Master_Login> Ipd_Master_Login { get; set; }
        public virtual DbSet<Ipd_Master_User> Ipd_Master_User { get; set; }
        public virtual DbSet<IpdPatientInfo> IpdPatientInfoes { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<Treatment> Treatments { get; set; }
        public virtual DbSet<Ward> Wards { get; set; }
    }
}
