//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class IpdPatientStatu
    {
        public int Id { get; set; }
        public Nullable<int> PatientId { get; set; }
        public string IPDStatus { get; set; }
        public Nullable<System.DateTime> AdmittedDateTime { get; set; }
        public Nullable<System.DateTime> DischargeDateTime { get; set; }
        public Nullable<System.DateTime> ReferDateTime { get; set; }
        public string ReferReasons { get; set; }
        public string ReferCaseSummary { get; set; }
        public Nullable<System.DateTime> LAMADateTime { get; set; }
        public string LAMAReasons { get; set; }
        public string LAMACaseSummary { get; set; }
        public Nullable<System.DateTime> DOPRDateTime { get; set; }
        public string DOPRReasons { get; set; }
        public string DOPRCaseSummary { get; set; }
        public Nullable<System.DateTime> DeathDateTime { get; set; }
        public string DeathReasons { get; set; }
        public string DeathCaseSummary { get; set; }
        public Nullable<System.DateTime> AbscondDateTime { get; set; }
        public string AbscondReasons { get; set; }
        public string AbscondCaseSummary { get; set; }
        public Nullable<System.DateTime> OtherDateTime { get; set; }
        public string OtherReasons { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    
        public virtual IpdPatientInfo IpdPatientInfo { get; set; }
    }
}
