//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class IpdPatientInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IpdPatientInfo()
        {
            this.IpdPatientLabReports = new HashSet<IpdPatientLabReport>();
            this.IpdRadioDiagnosisReports = new HashSet<IpdRadioDiagnosisReport>();
        }
    
        public int PatientId { get; set; }
        public string IpdNo { get; set; }
        public Nullable<System.DateTime> AdmittedDateTime { get; set; }
        public Nullable<int> TreatmentId { get; set; }
        public string MobileNumber { get; set; }
        public string Email { get; set; }
        public string Title { get; set; }
        public string PatientName { get; set; }
        public string MaritalStatus { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public Nullable<int> AreaId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> PinCode { get; set; }
        public string Religion { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> StateId { get; set; }
        public byte[] Photo { get; set; }
        public string FatherOrHusbandName { get; set; }
        public Nullable<System.DateTime> ValidUpto { get; set; }
        public string IDorAadharNumber { get; set; }
        public string IDNumber { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string RenewalStatusIPD { get; set; }
        public string RegistrationStatusIPD { get; set; }
        public Nullable<int> Age { get; set; }
        public string IPDStatus { get; set; }
    
        public virtual City City { get; set; }
        public virtual Department Department { get; set; }
        public virtual State State { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IpdPatientLabReport> IpdPatientLabReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IpdRadioDiagnosisReport> IpdRadioDiagnosisReports { get; set; }
    }
}
