//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class IpdPatientLabReport
    {
        public int Id { get; set; }
        public Nullable<int> PatientId { get; set; }
        public string HbCount { get; set; }
        public string PlateletCount { get; set; }
        public string MalariaParasite_Status { get; set; }
        public Nullable<System.DateTime> MalariaParasite_TestDate { get; set; }
        public string RapidKitNS1_Status { get; set; }
        public Nullable<System.DateTime> RapidKitNS1_TestDate { get; set; }
        public string RapidKitIGM_Status { get; set; }
        public Nullable<System.DateTime> RapidKitIGM_TestDate { get; set; }
        public string ELISANS1_Status { get; set; }
        public Nullable<System.DateTime> ELISANS1_TestDate { get; set; }
        public string ELISAIGM_Status { get; set; }
        public Nullable<System.DateTime> ELISAIGM_TestDate { get; set; }
        public string ELISAScrubTyphus_Status { get; set; }
        public Nullable<System.DateTime> ELISAScrubTyphus_TestDate { get; set; }
        public string ELISALaptospira_Status { get; set; }
        public Nullable<System.DateTime> ELISALaptospira_TestDate { get; set; }
        public string LFT_Details { get; set; }
        public string KFT_Details { get; set; }
        public string RandomDonerPlatelet_Count { get; set; }
        public Nullable<System.DateTime> RandomDonerPlatelet_TestDate { get; set; }
        public string SingleDonorPlatelet_Count { get; set; }
        public Nullable<System.DateTime> SingleDonorPlatelet_TestDate { get; set; }
        public string WholeBloodCell_Count { get; set; }
        public Nullable<System.DateTime> WholeBloodCell_TestDate { get; set; }
        public string PackedRBC_Count { get; set; }
        public Nullable<System.DateTime> PackedRBC_TestDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    
        public virtual IpdPatientInfo IpdPatientInfo { get; set; }
    }
}
